campeonato/core/urls.py
from django.conf.urls import url, include
from .views import *

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^inscricao/', inscricao, name='inscricao'),
    url(r'^combinacao/', combinacao, name='combinacao'),
    url(r'^absoluto/', absoluto, name='absoluto'),
    url(r'^resultado/', resultado, name='resultado'),
]

campeonato/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^jet/', include('jet.urls', 'jet')),
    url(r'^admin/', admin.site.urls),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^', include('campeonato.core.urls')),
]

campeonato/core/models.py
from django.db import models
from django.db.models import Q, F, Sum


class Equipe(models.Model):
    """
        Modelo de Equipes
    """

    nome = models.CharField(max_length=100)
    observacao = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.nome


class Academia(models.Model):
    """
        Modelo de Academia
    """

    nome = models.CharField(max_length=100)
    cidade = models.CharField(max_length=100)
    estado = models.CharField(max_length=2)
    equipe = models.ForeignKey('core.Equipe')

    def __str__(self):
        return self.nome


class Atleta(models.Model):
    """
        Modelo de Cadastro
    """

    MASC = 'Masculino'
    FEMI = 'Feminino'

    # tupla
    OPCAO = (
        ('M', MASC),
        ('F', FEMI),
    )

    FAIXA = (
        (1, 'Branca'),
        (2, 'Cinza / Branca'),
        (3, 'Cinza'),
        (4, 'Cinza / Preta'),
        (5, 'Amarela Branca'),
        (6, 'Amarela'),
        (7, 'Amarela / Preta'),
        (8, 'Laranja / Branca'),
        (9, 'Laranja'),
        (10, 'Laranja / Preta'),
        (11, 'Verde / Branca'),
        (12, 'Verde'),
        (13, 'Verde / Preta'),
        (14, 'Azul'),
        (15, 'Roxa'),
        (16, 'Marrom'),
        (17, 'Preta'),
        (18, 'Vermelha / Preta'),
        (19, 'Vermelha / Branca'),
        (20, 'Vermelha'),
    )

    nome = models.CharField(max_length=100, null=True)
    sexo = models.CharField(max_length=1, choices=OPCAO)
    idade = models.IntegerField(null=True, blank=True)
    peso = models.DecimalField(max_digits=15, decimal_places=2, default=0)
    faixa = models.IntegerField(choices=FAIXA, default=1)
    academia = models.ForeignKey('core.Academia')

    @property
    def faixa_convertida(self):
        # Valida Juvenio
        faixa = self.faixa if self.faixa > 13 else 1
        # Valida Marrom e preta
        faixa = faixa if faixa not in [16, 17] else 17
        return faixa

    def __str__(self):
        return self.nome


class InscricaoManager(models.Manager):
    def total_pago(self):
        total = 0
        queryset = self.get_queryset().filter(Q(pago_inscricao=True) or Q(pago_absoluto=True))

        for row in queryset:
            total += row.valor + row.valor_absoluto

        return total


class Inscricao(models.Model):
    CATEGORIA_PESO = (
        (1, 'Galo'),
        (2, 'Pluma'),
        (3, 'Pena'),
        (4, 'Leve'),
        (5, 'Médio'),
        (6, 'Meio Pesado'),
        (7, 'Pesado'),
        (8, 'Super Pesado'),
        (9, 'Pesadíssimo'),
    )

    CATEGORIA_IDADE = (
        (1, 'Pré-Mirin'),
        (2, 'Mirin'),
        (3, 'Infantil'),
        (4, 'Infanto Juvenil'),
        (7, 'Juvenil'),
        (5, 'Adulto'),
        (6, 'Master'),
    )

    objects = InscricaoManager()

    data = models.DateField()
    atleta = models.ForeignKey('core.Atleta')
    categoria_peso = models.IntegerField('Peso', choices=CATEGORIA_PESO, default=1)
    categoria_idade = models.IntegerField('Idade', choices=CATEGORIA_IDADE, default=5)
    absoluto = models.BooleanField(default=False)
    valor = models.DecimalField('valor da inscrição', max_digits=15, decimal_places=2, default=0, null=True, blank=True)
    valor_absoluto = models.DecimalField('valor absoluto', max_digits=15, decimal_places=2, default=0, null=True,
                                         blank=True)
    pago_inscricao = models.BooleanField('inscrição paga', default=False)
    pago_absoluto = models.BooleanField('absoluto pago', default=False)

    class Meta:
        verbose_name = 'inscrição'
        verbose_name_plural = 'incrições'

    def __str__(self):
        return self.atleta.nome


class Combinacao(models.Model):
    """
        Modelo de Possiveis confrotntos
    """

    chave = models.CharField(max_length=50)
    sexo = models.CharField(max_length=1, choices=Atleta.OPCAO)
    faixa = models.IntegerField(choices=Atleta.FAIXA)
    idade = models.IntegerField(choices=Inscricao.CATEGORIA_IDADE)
    peso = models.IntegerField(choices=Inscricao.CATEGORIA_PESO)
    inscricao = models.ManyToManyField('core.Inscricao')

    class Meta:
        verbose_name = 'combinação'
        verbose_name_plural = 'combinações'

    def __str__(self):
        return str(self.chave)


class CombinacaoAbsoluto(models.Model):
    """
        Modelo de Possiveis combinações absoluto
    """

    chave = models.CharField(max_length=50)
    sexo = models.CharField(max_length=1, choices=Atleta.OPCAO)
    faixa = models.IntegerField(choices=Atleta.FAIXA)
    idade = models.IntegerField(choices=Inscricao.CATEGORIA_IDADE)
    inscricao = models.ManyToManyField('core.Inscricao')

    class Meta:
        verbose_name = 'combinação absoluto'
        verbose_name_plural = 'combinações absoluto'

    def __str__(self):
        return str(self.chave)


class Chave(models.Model):
    """
    Modelo de chaves
    """
    sexo = models.CharField(max_length=1, choices=Atleta.OPCAO)
    faixa = models.IntegerField(choices=Atleta.FAIXA)
    idade = models.IntegerField(choices=Inscricao.CATEGORIA_IDADE)

    class Meta:
        verbose_name = 'chave'
        verbose_name_plural = 'chaves'

    def __str__(self):
        return '{}/{}/{}'.format(self.get_sexo_display(),
                                 self.get_faixa_display(),
                                 self.get_idade_display())


class Combate(models.Model):
    """
        Modelo de Combates
    """

    ETAPA = (
        (1, 'Oitava de Final'),
        (2, 'Quarta de Final'),
        (3, 'Semi de Final'),
        (4, 'Final'),
        (5, 'Outra'),
    )

    chave = models.ForeignKey('core.Chave')
    inscricao = models.ManyToManyField('core.Inscricao', through='core.CombateInfo')
    encerrada = models.BooleanField(default=False)

    class Meta:
        verbose_name = 'combate'
        verbose_name_plural = 'combates'

    def __str__(self):
        return '{}'.format(str(self.chave))


class CombateInfo(models.Model):
    """
    Modelo de informação do Combate
    """

    combate = models.ForeignKey('core.Combate')
    inscricao = models.ForeignKey('core.Inscricao')
    ponto = models.IntegerField(default=0)
    vantagem = models.IntegerField(default=0)
    punicao = models.IntegerField(default=0)

    class Meta:
        verbose_name_plural = 'informações dos combates'
        verbose_name = 'informação do combate'

    def __str__(self):
        return self.inscricao.atleta.nome


class CombateResultado(models.Model):
    TIPO = (
        (1, 'Finalização'),
        (2, 'Pontuação'),
        (3, 'Desistencia'),
        (4, 'W.O'),
        (5, 'Outro')
    )

    combate = models.ForeignKey('core.Combate')
    atleta = models.ForeignKey('core.CombateInfo')
    tipo_vitoria = models.IntegerField(choices=TIPO, default=1)
    tempo = models.TimeField()

    class Meta:
        verbose_name = 'resultado do combate'
        verbose_name_plural = 'resultados dos combates'

    def __str__(self):
        return '{}-{}'.format(str(self.combate.chave), self.combate.get_etapa_display())


class ResultadoManager(models.Manager):

    def academia(self):
        qr = self.get_queryset().all()

        return qr\
            .annotate(academia=F('atleta__atleta__academia__nome'))\
            .values('academia')\
            .annotate(
            total=Sum('pontos')
        ).order_by('-total')

    def equipe(self):
        qr = self.get_queryset().all()

        return qr\
            .annotate(equipe=F('atleta__atleta__academia__equipe__nome'))\
            .values('equipe')\
            .annotate(
            total=Sum('pontos')
        ).order_by('-total')

class Resultado(models.Model):
    objects = ResultadoManager()
    atleta = models.ForeignKey('core.Inscricao')
    absoluto = models.BooleanField(default=False)
    pontos = models.IntegerField(default=0)
    descricao = models.CharField(max_length=100, null=True, blank=True)

    class Meta:
        verbose_name_plural = 'resultados'
        verbose_name = 'resultado'
        unique_together = ('atleta', 'absoluto')

    def __str__(self):
        return self.atleta.atleta.nome

campeonato/core/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from django_pandas.io import read_frame

from .services import *
from .models import Combinacao, CombinacaoAbsoluto

# Create your views here.


def index(request):
    return render(request, 'home.html')

def absoluto(request):
    a = CombinacaoAbsoluto.objects.all().order_by('sexo', 'faixa', 'idade')
    return render(request, 'absoluto.html', dict(absoluto=a))


def inscricao(request):
    c = Combinacao.objects.all().order_by('sexo', 'faixa', 'idade', 'peso')
    return render(request, 'inscricao.html', dict(combinacoes= c))

def resultado(request):
    ac = Resultado.objects.academia()[:5]
    eq = Resultado.objects.equipe()[:5]

    return render(request, 'resultado.html', {'academia': ac, 'equipe': eq})

@login_required(login_url='/admin')
def combinacao(request):

    combinacao = SorteioService()
    combinacao.combinacao()
    combinacao.combinacao_absoluto()

    messages.success(request, 'Inscrições processadas com sucesso!')

    return redirect('inscricao')

campeonato/core/templates/absoluto.html
{% extends 'base.html' %}

{% block content %}
    <div class="row-fluid">
    <h3>Absoluto</h3>

        <div class="col-md-12">

            {% if messages %}
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <strong>Beleza!</strong>As inscrições foram reprocessadas!
                </div>
            {% endif %}

            <div class="row">
                <table class="bordered highlight responsive-table">
                    <thead>
                        <tr>
                            <th>Sexo</th>
                            <th>Faixa</th>
                            <th>Atletas</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for combinacao in absoluto %}
                        <tr>
                            <td>{{ combinacao.get_sexo_display }}</td>
                            <td>{{ combinacao.get_faixa_display }}</td>
                                <td>
                                    <ul>
                                    {% for inscricao in combinacao.inscricao.all %}
                                        <li> {{ inscricao.atleta.nome.title }} <small>{{ inscricao.atleta.academia.nome }}</small></li>
                                    {% endfor %}
                                    </ul>
                                </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>

    </div>

{% endblock %}

campeonato/core/templates/base.html
{% load staticfiles %}
<html>
<head>
    <title>Campeonato de Comodoro</title>
{#    <link rel="stylesheet" href="{%  static 'css/bootstrap.min.css' %}">#}
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link rel="stylesheet" href="{% static 'css/materialize.min.css' %}">
    <link href='//fonts.googleapis.com/css?family=Ubuntu&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>

<nav class="teal">
    <div class="nav-wrapper">
        <a href="#" class="brand-logo"></a>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li><a href="/inscricao">Categoria</a></li>
        <li><a href="/absoluto">Absoluto</a></li>
        <li><a href="/resultado">Resultado</a></li>
        <li><a href="/admin">Adminstração</a></li>
      </ul>
    </div>
  </nav>

<div class="container">
    {% block content %}
    {% endblock %}
</div>

<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'js/materialize.min.js' %}"></script>


<script>
    $(document).ready(function(){

        $(".alert-dismissible").fadeTo(2000, 1000).fadeOut(1000, function(){
            $(".alert-dismissible").fadeOut(1000);
        });

    })
</script>
</body>
</html>

campeonato/core/templates/chaves.html
{% extends 'base.html' %}

{% block content %}
    <div class="row-fluid">

        <div class="col-md-12">

            {% if messages %}
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <strong>Beleza!</strong>As inscrições foram reprocessadas!
                </div>
            {% endif %}

            <div class="row">
                <a class="btn btn-danger" href="{% url 'sorteio' %}">Reorganizar</a>
            </div>
            <br>

            <div class="row">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>Sexo</th>
                            <th>Faixa</th>
                            <th>Categoria</th>
                            <th>Peso</th>
                            <th>Atletas</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for combinacao in combinacoes %}
                        <tr>
                            <td>{{ combinacao.get_sexo_display }}</td>
                            <td>{{ combinacao.get_faixa_display }}</td>
                            <td>{{ combinacao.get_idade_display}}</td>
                            <td>{{ combinacao.get_peso_display }}</td>
                                <td>
                                    <ul>
                                    {% for inscricao in combinacao.inscricao.all %}
                                        <li> {{ inscricao.atleta.nome.title }} <small>{{ inscricao.atleta.academia.nome }}</small></li>
                                    {% endfor %}
                                    </ul>
                                </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>

    </div>




{% endblock %}

campeonato/core/templates/home.html
{% load static %}
<html>
<head>
    <title>Comodoro Open JJ</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{%  static 'css/bootstrap.min.css' %}">

    <style>
        .img-fluid{
            width: 100%;
            height: 100%;
            display: block;
        }
    </style>

</head>
<body>
    <div class="container">
        <div class="row">
            <img class="img-fluid" src="{% static  'images/index.png' %}">
        <div>
    </div>
</body>
</html>

campeonato/core/templates/inscricao.html
{% extends 'base.html' %}

{% block content %}
    <div class="row-fluid">
    <h3>Absoluto</h3>

        <div class="col-md-12">

            {% if messages %}
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <strong>Beleza!</strong>As inscrições foram reprocessadas!
                </div>
            {% endif %}

            <div class="row">
                <table class="bordered highlight responsive-table">
                    <thead>
                        <tr>
                            <th>Sexo</th>
                            <th>Faixa</th>
{#                            <th>Categoria</th>#}
{#                            <th>Peso</th>#}
                            <th>Atletas</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for combinacao in absoluto %}
                        <tr>
                            <td>{{ combinacao.get_sexo_display }}</td>
                            <td>{{ combinacao.get_faixa_display }}</td>
{#                            <td>{{ combinacao.get_idade_display}}</td>#}
{#                            <td>{{ combinacao.get_peso_display }}</td>#}
                                <td>
                                    <ul>
                                    {% for inscricao in combinacao.inscricao.all %}
                                        <li> {{ inscricao.atleta.nome.title }} <small>{{ inscricao.atleta.academia.nome }}</small></li>
                                    {% endfor %}
                                    </ul>
                                </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>

    </div>

{% endblock %}

campeonato/core/templates/resultado.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">
        <h3>Resultados - Academia</h3>

        <div class="col-6">
            <div class="row">
                <table class="bordered highlight responsive-table">
                    <thead>
                        <tr>
                            <th>Academia</th>
                            <th>Pontos</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for row in academia %}
                        <tr>
                            <td>{{ row.academia.title }}</td>
                            <td>{{ row.total }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>

    </div>

    <div class="row">
        <h3>Resultados - Equipe</h3>

        <div class="col-6">
            <div class="row">
                <table class="bordered highlight responsive-table">
                    <thead>
                        <tr>
                            <th>Equipe</th>
                            <th>Pontos</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for row in equipe %}
                        <tr>
                            <td>{{ row.equipe.title }}</td>
                            <td>{{ row.total }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>

    </div>

{% endblock %}